version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    versioning-strategy: "increase-if-necessary"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
